### ISSUE TITLE
In the data preparation, the audio_root requires a directory of .wav files, but the audio format in the Fisher dataset I downloaded is .sph.

### ISSUE THREAD

**Issue by tiamojames** [vivian556123/NeurIPS2024-CoVoMix#1]
![image](https://github.com/user-attachments/assets/4c2a3ccc-182e-4918-a56a-a4934af9c1d9)
In the data preparation, the audio_root requires a directory of .wav files, but the audio format in the Fisher dataset I downloaded is .sph.
🔍 Data Preparation
Ensure that you have already downloaded the Fisher English Dataset. If not, you need to first download it from https://catalog.ldc.upenn.edu/LDC2004T19.

Monologue Dataset Preparation
bash
python data_preparation/process_fisher_data.py \
   --audio_root=<audio (.wav) directory>
   --transcript_root=<LDC Fisher dataset directory> \
   --dest_root=<destination directory> \
   --data_sets=LDC2004S13-Part1,LDC2005S13-Part2 \
   --remove_noises \
   --min_slice_duration 10 \

**Comment by vivian556123** [comment]
Hi, you need to first process the Fisher dataset into wav format. It is normal that the downloaded data has a .sph format. 
You can use **sph2pipe** for processing the dataset:

```
wget https://www.openslr.org/resources/3/sph2pipe_v2.5.tar.gz
tar -xvf sph2pipe_v2.5.tar.gz
find your_fisher_path -type f -name "*.sph" -exec sh -c './sph2pipe -f wav $0 ${0%.sph}.wav | echo "Converting $0 to ${0%.sph}.wav"' {} \;
```

**Comment by tiamojames** [comment]
> Hi, you need to first process the Fisher dataset into wav format. It is normal that the downloaded data has a .sph format. You can use **sph2pipe** for processing the dataset:
> 
> ```
> wget https://www.openslr.org/resources/3/sph2pipe_v2.5.tar.gz
> tar -xvf sph2pipe_v2.5.tar.gz
> find your_fisher_path -type f -name "*.sph" -exec sh -c './sph2pipe -f wav $0 ${0%.sph}.wav | echo "Converting $0 to ${0%.sph}.wav"' {} \;
> ```
Hi, your suggestion to use sph2pipe for converting the Fisher dataset from .sph to .wav worked perfectly. I got wav format audio successfully.  thanks for your help!
